### ISSUE TITLE
net.Socket is not a constructor

### ISSUE THREAD

**Issue by Kiran-N** [vdemedes/net-socket#2]
Below is the client code I am using to connect to the socket. It gives me a error net.socket is not a constructor. 

```
[var net = require('net-socket');
var SocketService = (function () {
    function SocketService() {
    }
    SocketService.prototype.startDevice = function () {
        var socket = net.connect(5555, 'localhost');
        socket.setEncoding('utf8');
        socket.on('connect', function () {
            socket.end('[START]');
            socket.destroy();
        });
    };
    return SocketService;
}());](url)
```

![image](https://cloud.githubusercontent.com/assets/17794731/21065200/9ac4fabc-be24-11e6-9229-4e53fc2e0aa9.png)

![image](https://cloud.githubusercontent.com/assets/17794731/21065217/b257f594-be24-11e6-8fae-12821196723a.png)

Any reason why this is happening.

**Comment by vadimdemedes** [comment]
This module is meant to be used only on Node.js, not in browsers.

**Comment by Kiran-N** [comment]
Thank you, got it.
